### ISSUE TITLE
您好，网址链接炸了，能否补一下

### ISSUE THREAD

**Issue by Norach-I** [yq1ng/healthCheck-in#1]
readme中的以下部分，链接访问失败。

更详细的教程与抓包分析在这：https://yq1ng.github.io/z_post/%E8%87%AA%E5%8A%A8%E5%8C%96%E5%81%A5%E5%BA%B7%E6%89%93%E5%8D%A1/

**Comment by yq1ng** [comment]
抱歉，博客更新了，新地址如下
https://yq1ng.github.io/2021/03/27/zi-dong-hua-jian-kang-da-qia/
稍后更新readme

**Comment by Norach-I** [comment]
感谢~我想请教一下响应部分的代码模拟，有没有教程推荐看看的。我想看的是0x02 抓包&分析部分，以为会更全面的。https://www.icode9.com/content-4-904817.html这个网址搬运了你的文章，看到这个搬运的才找过来的。

**Comment by yq1ng** [comment]
响应部分的代码模拟是什么意思？抓包？还是代码问题

**Comment by Norach-I** [comment]
就是这种，抓包成功了，写对应代码就懵了。。。。。。不清楚哪些可以做字典的Key，哪些可以跳过不去考虑。
![image](https://user-images.githubusercontent.com/51918042/147722148-aa2725e9-e95f-4623-95a6-b93352440ddc.png)

![image](https://user-images.githubusercontent.com/51918042/147722288-72747f16-1f52-40c2-9b75-fbdaf93e1922.png)

**Comment by yq1ng** [comment]
我使用了python的requests库，网上很多教程，你可以参考看看
https://www.liaoxuefeng.com/wiki/1016959663602400/1183249464292448

**Comment by Norach-I** [comment]
代码图是对应填写，就能实现自动打卡的，但我对比抓包的响应部分，发现township这些并没有，而抓包的部分例如 data下的id，代码中也并没有体现出来。。。。这个是我们学校以前用的打卡小程序，G码云上面的一个项目实现自动打卡。然后现在换小程序了，我想依照G码云这个做蓝本修改，抓包分析这部分就出了问题，查找参考的时候，找到了您这个项目的博客文章。

**Comment by yq1ng** [comment]
不清楚欸，返回id可能是前端要用的吧

**Comment by Norach-I** [comment]
OK，谢谢~~~
